import type { Grade } from '../generated/prisma/enums.js';
import type { ItemDef, SkillDef, WorldDef } from './math-foundation.js';

/**
 * Phase 6 — Platform Expansion. Each subject is only data: skills with
 * prerequisites, worlds with stages and a boss, and where placement starts.
 * The learning engine (placement, mastery, path, review, quests, rewards,
 * assignments, reports) is shared with mathematics unchanged.
 * Skill arrays are in curriculum order and must stay topological.
 */

export interface CurriculumDef {
  skills: SkillDef[];
  worlds: WorldDef[];
  placementStart: Partial<Record<Grade, string>>;
  items: ItemDef[];
}

// ───────────── 🔤 English ─────────────

export const ENGLISH: CurriculumDef = {
  skills: [
    { code: 'EN_LETTERS', group: 'EN_ALPHABET', name: 'Letters', nameTh: 'ตัวอักษร A–Z', grade: 'K1', prerequisites: [] },
    { code: 'EN_PHONICS', group: 'EN_ALPHABET', name: 'Phonics', nameTh: 'เสียงตัวอักษร', grade: 'K2', prerequisites: ['EN_LETTERS'] },
    { code: 'EN_VOCAB_PICTURE', group: 'EN_VOCABULARY', name: 'Picture Words', nameTh: 'คำศัพท์จากภาพ', grade: 'K3', prerequisites: ['EN_LETTERS'] },
    { code: 'EN_NUMBERS', group: 'EN_VOCABULARY', name: 'Numbers', nameTh: 'ตัวเลขภาษาอังกฤษ', grade: 'K3', prerequisites: ['EN_LETTERS'] },
    { code: 'EN_VOCAB_MEANING', group: 'EN_VOCABULARY', name: 'Word Meanings', nameTh: 'ความหมายคำศัพท์', grade: 'P1', prerequisites: ['EN_VOCAB_PICTURE'] },
    { code: 'EN_SPELLING', group: 'EN_VOCABULARY', name: 'Spelling', nameTh: 'การสะกดคำ', grade: 'P2', prerequisites: ['EN_PHONICS', 'EN_VOCAB_PICTURE'] },
    { code: 'EN_GRAMMAR', group: 'EN_GRAMMAR', name: 'Grammar', nameTh: 'ไวยากรณ์พื้นฐาน', grade: 'P3', prerequisites: ['EN_VOCAB_MEANING'] },
    { code: 'EN_CONVERSATION', group: 'EN_COMMUNICATION', name: 'Everyday Talk', nameTh: 'บทสนทนาในชีวิตประจำวัน', grade: 'P3', prerequisites: ['EN_VOCAB_MEANING', 'EN_NUMBERS'] },
    { code: 'EN_PREPOSITIONS', group: 'EN_GRAMMAR', name: 'Prepositions', nameTh: 'คำบุพบทบอกตำแหน่งและเวลา', grade: 'P4', prerequisites: ['EN_GRAMMAR'] },
    { code: 'EN_SENTENCES', group: 'EN_GRAMMAR', name: 'Sentence Order', nameTh: 'การเรียงประโยค', grade: 'P4', prerequisites: ['EN_GRAMMAR'] },
    { code: 'EN_TENSES', group: 'EN_GRAMMAR', name: 'Tenses', nameTh: 'กาลของกริยา (Tense)', grade: 'P5', prerequisites: ['EN_SENTENCES'] },
    { code: 'EN_READING', group: 'EN_COMMUNICATION', name: 'Reading Stories', nameTh: 'อ่านเรื่องสั้นภาษาอังกฤษ', grade: 'P6', prerequisites: ['EN_SENTENCES', 'EN_CONVERSATION', 'EN_PREPOSITIONS'] },
  ],
  placementStart: { K1: 'EN_LETTERS', K2: 'EN_LETTERS', K3: 'EN_PHONICS', P1: 'EN_VOCAB_PICTURE', P2: 'EN_VOCAB_MEANING', P3: 'EN_SPELLING', P4: 'EN_GRAMMAR', P5: 'EN_GRAMMAR', P6: 'EN_SENTENCES' },
  worlds: [
    {
      code: 'ABC_TOWN',
      name: 'ABC Town',
      nameTh: 'เมืองตัวอักษร ABC',
      emoji: '🔤',
      theme: 'abc',
      stages: [
        { skill: 'EN_LETTERS', name: 'ร้องเพลง ABC', activity: 'TARGET', difficulty: 1 },
        { skill: 'EN_LETTERS', name: 'ตัวพิมพ์ใหญ่-เล็ก', activity: 'PUZZLE', difficulty: 3 },
        { skill: 'EN_PHONICS', name: 'เสียงขึ้นต้น', activity: 'FISHING', difficulty: 1 },
        { skill: 'EN_PHONICS', name: 'เสียงเหมือนกัน', activity: 'TRAIN', difficulty: 4 },
      ],
      boss: { name: 'นกแก้วพูดเก่ง', emoji: '🦜', difficulty: 2 },
    },
    {
      code: 'WORD_JUNGLE',
      name: 'Word Jungle',
      nameTh: 'ป่าคำศัพท์',
      emoji: '🌴',
      theme: 'jungle',
      stages: [
        { skill: 'EN_VOCAB_PICTURE', name: 'สัตว์ในป่า', activity: 'TARGET', difficulty: 1 },
        { skill: 'EN_VOCAB_PICTURE', name: 'สีสันในป่า', activity: 'MAGIC', difficulty: 3 },
        { skill: 'EN_VOCAB_MEANING', name: 'แปลความหมาย', activity: 'PUZZLE', difficulty: 2 },
        { skill: 'EN_SPELLING', name: 'สะกดคำหาย', activity: 'BUILDING', difficulty: 1 },
        { skill: 'EN_SPELLING', name: 'คำไหนสะกดถูก', activity: 'RACING', difficulty: 4 },
        { skill: 'EN_GRAMMAR', name: 'am is are', activity: 'TRAIN', difficulty: 1 },
        { skill: 'EN_GRAMMAR', name: 'เติมประโยค', activity: 'MAGIC', difficulty: 4 },
      ],
      boss: { name: 'ราชสีห์แกรมมาร์', emoji: '🦁', difficulty: 3 },
    },
    {
      code: 'ENGLISH_SCHOOL',
      name: 'English School',
      nameTh: 'โรงเรียนภาษาอังกฤษ',
      emoji: '🏫',
      theme: 'school',
      stages: [
        { skill: 'EN_NUMBERS', name: 'นับเลขกับครูนกฮูก', activity: 'TARGET', difficulty: 1 },
        { skill: 'EN_NUMBERS', name: 'เลข teen กับ ty', activity: 'RACING', difficulty: 3 },
        { skill: 'EN_NUMBERS', name: 'คณิตภาษาอังกฤษ', activity: 'MAGIC', difficulty: 5 },
        { skill: 'EN_CONVERSATION', name: 'สวัสดีเพื่อนใหม่', activity: 'SHOP', difficulty: 1 },
        { skill: 'EN_CONVERSATION', name: 'ถาม-ตอบในห้องเรียน', activity: 'TRAIN', difficulty: 3 },
        { skill: 'EN_CONVERSATION', name: 'ขอทางไปห้องสมุด', activity: 'PUZZLE', difficulty: 5 },
        { skill: 'EN_PREPOSITIONS', name: 'แมวซ่อนอยู่ไหน', activity: 'FISHING', difficulty: 1 },
        { skill: 'EN_PREPOSITIONS', name: 'in on at', activity: 'BUILDING', difficulty: 4 },
      ],
      boss: { name: 'ครูนกฮูกจอมพูด', emoji: '🦉', difficulty: 3 },
    },
    {
      code: 'STORY_CITY',
      name: 'Story City',
      nameTh: 'เมืองนิทานอังกฤษ',
      emoji: '🗽',
      theme: 'storycity',
      stages: [
        { skill: 'EN_SENTENCES', name: 'ต่อประโยคสั้น', activity: 'BUILDING', difficulty: 1 },
        { skill: 'EN_SENTENCES', name: 'ประโยคคำถาม', activity: 'TRAIN', difficulty: 4 },
        { skill: 'EN_TENSES', name: 'ทำทุกวันหรือกำลังทำ', activity: 'RACING', difficulty: 1 },
        { skill: 'EN_TENSES', name: 'เมื่อวานกับพรุ่งนี้', activity: 'MAGIC', difficulty: 3 },
        { skill: 'EN_TENSES', name: 'นักเดินทางข้ามเวลา', activity: 'TARGET', difficulty: 5 },
        { skill: 'EN_READING', name: 'นิทานสุนัขแสนรู้', activity: 'PUZZLE', difficulty: 1 },
        { skill: 'EN_READING', name: 'วันหยุดที่ชายหาด', activity: 'FISHING', difficulty: 3 },
        { skill: 'EN_READING', name: 'นักอ่านตัวยง', activity: 'TRAIN', difficulty: 5 },
      ],
      boss: { name: 'มังกรนักเล่านิทาน', emoji: '🐲', difficulty: 3 },
    },
    {
      code: 'WORD_MINE',
      name: 'Word Mine',
      nameTh: 'เหมืองบล็อกคำศัพท์',
      emoji: '🧱',
      theme: 'mine',
      stages: [
        { skill: 'EN_VOCAB_PICTURE', name: 'ขุดหาคำศัพท์', activity: 'MINING', difficulty: 2 },
        { skill: 'EN_NUMBERS', name: 'นับแร่เป็นภาษาอังกฤษ', activity: 'MINING', difficulty: 3 },
        { skill: 'EN_SPELLING', name: 'สร้างคำทีละบล็อก', activity: 'BUILDING', difficulty: 2 },
        { skill: 'EN_PREPOSITIONS', name: 'บล็อกอยู่ตรงไหน', activity: 'BUILDING', difficulty: 2 },
        { skill: 'EN_SENTENCES', name: 'ต่อบล็อกประโยค', activity: 'MINING', difficulty: 3 },
        { skill: 'EN_TENSES', name: 'อุโมงค์กาลเวลา', activity: 'MINING', difficulty: 3 },
      ],
      boss: { name: 'ค้างคาวถ้ำคำศัพท์', emoji: '🦇', difficulty: 3 },
    },
  ],
  items: [
    { code: 'PARROT_GOLD', name: 'นกแก้วทอง', slot: 'PET', emoji: '🦜', price: null, rewardWorldCode: 'ABC_TOWN' },
    { code: 'EXPLORER_HAT', name: 'หมวกซาฟารี', slot: 'HAT', emoji: '🤠', price: null, rewardWorldCode: 'WORD_JUNGLE' },
    { code: 'ABC_BLOCKS', name: 'บล็อกตัวอักษร', slot: 'ACCESSORY', emoji: '🔠', price: null, rewardWorldCode: 'ENGLISH_SCHOOL' },
    { code: 'STORY_DRAGON', name: 'มังกรน้อยนักเล่าเรื่อง', slot: 'PET', emoji: '🐲', price: null, rewardWorldCode: 'STORY_CITY' },
    { code: 'ENCHANTED_BOOK', name: 'หนังสือเวทบล็อก', slot: 'ACCESSORY', emoji: '📗', price: null, rewardWorldCode: 'WORD_MINE' },
  ],
};

// ───────────── 🔬 Science ─────────────

export const SCIENCE: CurriculumDef = {
  skills: [
    { code: 'SCI_LIVING', group: 'SCI_LIFE', name: 'Living Things', nameTh: 'สิ่งมีชีวิตและไม่มีชีวิต', grade: 'P1', prerequisites: [] },
    { code: 'SCI_ANIMALS', group: 'SCI_LIFE', name: 'Animals', nameTh: 'สัตว์รอบตัว', grade: 'P2', prerequisites: ['SCI_LIVING'] },
    { code: 'SCI_PLANTS', group: 'SCI_LIFE', name: 'Plants', nameTh: 'พืชรอบตัว', grade: 'P2', prerequisites: ['SCI_LIVING'] },
    { code: 'SCI_WEATHER', group: 'SCI_EARTH', name: 'Weather & Seasons', nameTh: 'ลมฟ้าอากาศและฤดูกาล', grade: 'P2', prerequisites: [] },
    { code: 'SCI_BODY', group: 'SCI_LIFE', name: 'Human Body', nameTh: 'ร่างกายของเรา', grade: 'P3', prerequisites: ['SCI_LIVING'] },
    { code: 'SCI_LIFE_CYCLES', group: 'SCI_LIFE', name: 'Life Cycles', nameTh: 'วัฏจักรชีวิต', grade: 'P3', prerequisites: ['SCI_ANIMALS', 'SCI_PLANTS'] },
    { code: 'SCI_HEALTH', group: 'SCI_LIFE', name: 'Health & Nutrition', nameTh: 'สุขภาพและอาหาร', grade: 'P3', prerequisites: ['SCI_BODY'] },
    { code: 'SCI_MATTER', group: 'SCI_PHYSICAL', name: 'States of Matter', nameTh: 'สสารและสถานะ', grade: 'P4', prerequisites: [] },
    { code: 'SCI_ECOSYSTEM', group: 'SCI_LIFE', name: 'Ecosystems', nameTh: 'ระบบนิเวศและห่วงโซ่อาหาร', grade: 'P4', prerequisites: ['SCI_LIFE_CYCLES'] },
    { code: 'SCI_LIGHT_SOUND', group: 'SCI_PHYSICAL', name: 'Light & Sound', nameTh: 'แสงและเสียง', grade: 'P4', prerequisites: ['SCI_MATTER'] },
    { code: 'SCI_EARTH_SPACE', group: 'SCI_EARTH', name: 'Earth & Space', nameTh: 'โลกและอวกาศ', grade: 'P5', prerequisites: ['SCI_MATTER', 'SCI_WEATHER'] },
    { code: 'SCI_ROCKS_SOIL', group: 'SCI_EARTH', name: 'Rocks & Soil', nameTh: 'หิน ดิน และเปลือกโลก', grade: 'P5', prerequisites: ['SCI_MATTER'] },
    { code: 'SCI_EXPERIMENT', group: 'SCI_INQUIRY', name: 'Scientific Method', nameTh: 'ทดลองแบบนักวิทยาศาสตร์', grade: 'P5', prerequisites: ['SCI_MATTER'] },
    { code: 'SCI_ENERGY', group: 'SCI_PHYSICAL', name: 'Energy & Forces', nameTh: 'พลังงานและแรง', grade: 'P6', prerequisites: ['SCI_MATTER'] },
    { code: 'SCI_ELECTRICITY', group: 'SCI_PHYSICAL', name: 'Electricity', nameTh: 'ไฟฟ้าและวงจรไฟฟ้า', grade: 'P6', prerequisites: ['SCI_ENERGY'] },
  ],
  placementStart: { K1: 'SCI_LIVING', K2: 'SCI_LIVING', K3: 'SCI_LIVING', P1: 'SCI_LIVING', P2: 'SCI_ANIMALS', P3: 'SCI_BODY', P4: 'SCI_MATTER', P5: 'SCI_MATTER', P6: 'SCI_EARTH_SPACE' },
  worlds: [
    {
      code: 'NATURE_LAB',
      name: 'Nature Lab',
      nameTh: 'ห้องแล็บธรรมชาติ',
      emoji: '🌿',
      theme: 'lab',
      stages: [
        { skill: 'SCI_LIVING', name: 'มีชีวิตหรือไม่', activity: 'TARGET', difficulty: 1 },
        { skill: 'SCI_ANIMALS', name: 'บ้านของสัตว์', activity: 'FISHING', difficulty: 1 },
        { skill: 'SCI_ANIMALS', name: 'ห่วงโซ่อาหาร', activity: 'PUZZLE', difficulty: 4 },
        { skill: 'SCI_PLANTS', name: 'ปลูกต้นไม้', activity: 'BUILDING', difficulty: 2 },
        { skill: 'SCI_BODY', name: 'ประสาทสัมผัส', activity: 'MAGIC', difficulty: 1 },
        { skill: 'SCI_BODY', name: 'อวัยวะภายใน', activity: 'MAGIC', difficulty: 4 },
      ],
      boss: { name: 'ไดโนเสาร์นักวิทย์', emoji: '🦕', difficulty: 3 },
    },
    {
      code: 'SCIENCE_STATION',
      name: 'Science Station',
      nameTh: 'สถานีวิทยาศาสตร์',
      emoji: '🧪',
      theme: 'station',
      stages: [
        { skill: 'SCI_MATTER', name: 'แข็ง เหลว แก๊ส', activity: 'MAGIC', difficulty: 1 },
        { skill: 'SCI_MATTER', name: 'การเปลี่ยนสถานะ', activity: 'PUZZLE', difficulty: 3 },
        { skill: 'SCI_EARTH_SPACE', name: 'กลางวันกลางคืน', activity: 'RACING', difficulty: 2 },
        { skill: 'SCI_EARTH_SPACE', name: 'ระบบสุริยะ', activity: 'TARGET', difficulty: 4 },
        { skill: 'SCI_ENERGY', name: 'ไฟฟ้าและเสียง', activity: 'TRAIN', difficulty: 2 },
        { skill: 'SCI_ENERGY', name: 'แรงและพลังงาน', activity: 'BUILDING', difficulty: 4 },
      ],
      boss: { name: 'หุ่นยนต์ไอน์สไตน์', emoji: '🤖', difficulty: 3 },
    },
    {
      code: 'WEATHER_GARDEN',
      name: 'Weather Garden',
      nameTh: 'สวนฟ้าฝนและชีวิต',
      emoji: '🌦️',
      theme: 'garden',
      stages: [
        { skill: 'SCI_WEATHER', name: 'วันนี้อากาศเป็นอย่างไร', activity: 'TARGET', difficulty: 1 },
        { skill: 'SCI_WEATHER', name: 'สามฤดูของไทย', activity: 'RACING', difficulty: 2 },
        { skill: 'SCI_WEATHER', name: 'เมฆ ลม และฟ้าผ่า', activity: 'MAGIC', difficulty: 4 },
        { skill: 'SCI_LIFE_CYCLES', name: 'ไข่ใบนี้จะกลายเป็นอะไร', activity: 'PUZZLE', difficulty: 1 },
        { skill: 'SCI_LIFE_CYCLES', name: 'ผีเสื้อแสนสวย', activity: 'BUILDING', difficulty: 3 },
        { skill: 'SCI_HEALTH', name: 'เด็กสุขภาพดี', activity: 'SHOP', difficulty: 1 },
        { skill: 'SCI_HEALTH', name: 'นักสู้เชื้อโรค', activity: 'TARGET', difficulty: 4 },
        { skill: 'SCI_ECOSYSTEM', name: 'ห่วงโซ่อาหาร', activity: 'TRAIN', difficulty: 2 },
        { skill: 'SCI_ECOSYSTEM', name: 'สมดุลธรรมชาติ', activity: 'FISHING', difficulty: 4 },
      ],
      boss: { name: 'ยักษ์เมฆฝนฟ้าคะนอง', emoji: '⛈️', difficulty: 3 },
    },
    {
      code: 'DISCOVERY_LAB',
      name: 'Discovery Lab',
      nameTh: 'ห้องทดลองนักค้นพบ',
      emoji: '🔭',
      theme: 'discovery',
      stages: [
        { skill: 'SCI_LIGHT_SOUND', name: 'เงามหัศจรรย์', activity: 'PUZZLE', difficulty: 1 },
        { skill: 'SCI_LIGHT_SOUND', name: 'กระจกและรุ้ง', activity: 'MAGIC', difficulty: 4 },
        { skill: 'SCI_ROCKS_SOIL', name: 'นักสำรวจดิน', activity: 'MINING', difficulty: 1 },
        { skill: 'SCI_ROCKS_SOIL', name: 'หินสามแบบ', activity: 'MINING', difficulty: 3 },
        { skill: 'SCI_EXPERIMENT', name: 'ตั้งคำถามแบบนักวิทย์', activity: 'TRAIN', difficulty: 2 },
        { skill: 'SCI_EXPERIMENT', name: 'การทดลองที่ยุติธรรม', activity: 'RACING', difficulty: 4 },
        { skill: 'SCI_ELECTRICITY', name: 'จุดไฟให้หลอดไฟ', activity: 'TARGET', difficulty: 1 },
        { skill: 'SCI_ELECTRICITY', name: 'วงจรอนุกรมและขนาน', activity: 'MAGIC', difficulty: 4 },
      ],
      boss: { name: 'ศาสตราจารย์สายฟ้า', emoji: '🧑‍🔬', difficulty: 3 },
    },
    {
      code: 'CRYSTAL_CAVE',
      name: 'Crystal Cave',
      nameTh: 'ถ้ำผลึกนักวิทย์',
      emoji: '💎',
      theme: 'craft',
      stages: [
        { skill: 'SCI_MATTER', name: 'ขุดน้ำแข็งกับลาวา', activity: 'MINING', difficulty: 2 },
        { skill: 'SCI_ROCKS_SOIL', name: 'ชั้นหินใต้ดิน', activity: 'MINING', difficulty: 2 },
        { skill: 'SCI_ROCKS_SOIL', name: 'ฟอสซิลในถ้ำ', activity: 'MINING', difficulty: 4 },
        { skill: 'SCI_PLANTS', name: 'ฟาร์มบล็อกพืชผัก', activity: 'BUILDING', difficulty: 3 },
        { skill: 'SCI_ECOSYSTEM', name: 'ระบบนิเวศในถ้ำ', activity: 'MINING', difficulty: 3 },
        { skill: 'SCI_ELECTRICITY', name: 'วงจรไฟส่องถ้ำ', activity: 'BUILDING', difficulty: 2 },
      ],
      boss: { name: 'ยักษ์ลาวา', emoji: '🌋', difficulty: 4 },
    },
  ],
  items: [
    { code: 'MICROSCOPE', name: 'กล้องจุลทรรศน์', slot: 'ACCESSORY', emoji: '🔬', price: null, rewardWorldCode: 'NATURE_LAB' },
    { code: 'LAB_COAT', name: 'เสื้อกาวน์นักวิทย์', slot: 'OUTFIT', emoji: '🥼', price: null, rewardWorldCode: 'SCIENCE_STATION' },
    { code: 'RAINBOW_UMBRELLA', name: 'ร่มสายรุ้ง', slot: 'ACCESSORY', emoji: '🌂', price: null, rewardWorldCode: 'WEATHER_GARDEN' },
    { code: 'LIGHT_BULB', name: 'หลอดไฟไอเดีย', slot: 'HAT', emoji: '💡', price: null, rewardWorldCode: 'DISCOVERY_LAB' },
    { code: 'CRYSTAL_BALL', name: 'ลูกแก้วผลึก', slot: 'ACCESSORY', emoji: '🔮', price: null, rewardWorldCode: 'CRYSTAL_CAVE' },
  ],
};

// ───────────── 📖 Thai reading ─────────────

export const READING: CurriculumDef = {
  skills: [
    { code: 'TH_CONSONANTS', group: 'TH_LETTERS', name: 'Thai Consonants', nameTh: 'พยัญชนะไทย', grade: 'K1', prerequisites: [] },
    { code: 'TH_VOWELS', group: 'TH_LETTERS', name: 'Thai Vowels', nameTh: 'สระไทย', grade: 'K2', prerequisites: ['TH_CONSONANTS'] },
    { code: 'TH_WORDS', group: 'TH_READING', name: 'Reading Words', nameTh: 'อ่านคำ', grade: 'K3', prerequisites: ['TH_VOWELS'] },
    { code: 'TH_TONES', group: 'TH_LETTERS', name: 'Tone Marks', nameTh: 'วรรณยุกต์', grade: 'P1', prerequisites: ['TH_WORDS'] },
    { code: 'TH_SPELLING', group: 'TH_WRITING', name: 'Spelling', nameTh: 'การสะกดคำ', grade: 'P1', prerequisites: ['TH_WORDS'] },
    { code: 'TH_COMPREHENSION', group: 'TH_READING', name: 'Reading Comprehension', nameTh: 'อ่านจับใจความ', grade: 'P2', prerequisites: ['TH_WORDS'] },
    { code: 'TH_VOCAB', group: 'TH_READING', name: 'Word Meanings', nameTh: 'ความหมายของคำ', grade: 'P2', prerequisites: ['TH_WORDS'] },
    { code: 'TH_FINAL_SOUNDS', group: 'TH_WRITING', name: 'Final Consonants', nameTh: 'มาตราตัวสะกด', grade: 'P2', prerequisites: ['TH_SPELLING', 'TH_TONES'] },
    { code: 'TH_CLASSIFIERS', group: 'TH_GRAMMAR', name: 'Classifiers', nameTh: 'คำลักษณนาม', grade: 'P3', prerequisites: ['TH_VOCAB'] },
    { code: 'TH_SENTENCES', group: 'TH_GRAMMAR', name: 'Sentences', nameTh: 'ประโยคและคำเชื่อม', grade: 'P3', prerequisites: ['TH_VOCAB'] },
    { code: 'TH_IDIOMS', group: 'TH_LITERATURE', name: 'Idioms & Proverbs', nameTh: 'สำนวนและสุภาษิต', grade: 'P5', prerequisites: ['TH_SENTENCES'] },
    { code: 'TH_COMPREHENSION_ADV', group: 'TH_READING', name: 'Critical Reading', nameTh: 'อ่านคิดวิเคราะห์', grade: 'P5', prerequisites: ['TH_COMPREHENSION', 'TH_SENTENCES'] },
    { code: 'TH_WORD_TYPES', group: 'TH_GRAMMAR', name: 'Parts of Speech', nameTh: 'ชนิดของคำ', grade: 'P6', prerequisites: ['TH_SENTENCES', 'TH_CLASSIFIERS'] },
  ],
  placementStart: { K1: 'TH_CONSONANTS', K2: 'TH_CONSONANTS', K3: 'TH_VOWELS', P1: 'TH_WORDS', P2: 'TH_WORDS', P3: 'TH_SPELLING', P4: 'TH_COMPREHENSION', P5: 'TH_VOCAB', P6: 'TH_SENTENCES' },
  worlds: [
    {
      code: 'KOR_KAI_VILLAGE',
      name: 'Kor Kai Village',
      nameTh: 'หมู่บ้าน ก ไก่',
      emoji: '🐔',
      theme: 'korkai',
      stages: [
        { skill: 'TH_CONSONANTS', name: 'ก ไก่ ข ไข่', activity: 'TARGET', difficulty: 1 },
        { skill: 'TH_CONSONANTS', name: 'เรียง ก–ฮ', activity: 'TRAIN', difficulty: 3 },
        { skill: 'TH_VOWELS', name: 'สระเสียงยาว', activity: 'FISHING', difficulty: 1 },
        { skill: 'TH_VOWELS', name: 'สระประสม', activity: 'MAGIC', difficulty: 4 },
        { skill: 'TH_WORDS', name: 'อ่านคำจากภาพ', activity: 'PUZZLE', difficulty: 1 },
      ],
      boss: { name: 'ไก่ชนจอมพยัญชนะ', emoji: '🐓', difficulty: 2 },
    },
    {
      code: 'STORY_LIBRARY',
      name: 'Story Library',
      nameTh: 'ห้องสมุดนิทาน',
      emoji: '📚',
      theme: 'library',
      stages: [
        { skill: 'TH_WORDS', name: 'คำมีวรรณยุกต์', activity: 'BUILDING', difficulty: 3 },
        { skill: 'TH_SPELLING', name: 'คำไหนเขียนถูก', activity: 'TARGET', difficulty: 2 },
        { skill: 'TH_SPELLING', name: 'คำยากระดับเซียน', activity: 'RACING', difficulty: 4 },
        { skill: 'TH_COMPREHENSION', name: 'นิทานสั้น', activity: 'MAGIC', difficulty: 1 },
        { skill: 'TH_COMPREHENSION', name: 'ข้อคิดจากเรื่อง', activity: 'PUZZLE', difficulty: 4 },
      ],
      boss: { name: 'หนอนหนังสือยักษ์', emoji: '🐛', difficulty: 3 },
    },
    {
      code: 'FLOATING_MARKET',
      name: 'Floating Word Market',
      nameTh: 'ตลาดน้ำคำไทย',
      emoji: '🛶',
      theme: 'floating',
      stages: [
        { skill: 'TH_TONES', name: 'เรือวรรณยุกต์', activity: 'FISHING', difficulty: 1 },
        { skill: 'TH_TONES', name: 'เสียงสูงเสียงต่ำ', activity: 'TARGET', difficulty: 3 },
        { skill: 'TH_VOCAB', name: 'คำตรงข้ามลอยน้ำ', activity: 'SHOP', difficulty: 1 },
        { skill: 'TH_VOCAB', name: 'คำสุภาพแม่ค้า', activity: 'PUZZLE', difficulty: 3 },
        { skill: 'TH_FINAL_SOUNDS', name: 'แม่ ก กา พาเที่ยว', activity: 'BUILDING', difficulty: 1 },
        { skill: 'TH_FINAL_SOUNDS', name: 'ตัวสะกดตัวป่วน', activity: 'TRAIN', difficulty: 4 },
        { skill: 'TH_CLASSIFIERS', name: 'นับของในเรือ', activity: 'SHOP', difficulty: 1 },
        { skill: 'TH_CLASSIFIERS', name: 'ลักษณนามพิเศษ', activity: 'MAGIC', difficulty: 4 },
      ],
      boss: { name: 'จระเข้จอมคำ', emoji: '🐊', difficulty: 3 },
    },
    {
      code: 'WISDOM_PALACE',
      name: 'Wisdom Palace',
      nameTh: 'วังปราชญ์',
      emoji: '🏛️',
      theme: 'palace',
      stages: [
        { skill: 'TH_SENTENCES', name: 'ต่อประโยคให้ครบ', activity: 'BUILDING', difficulty: 1 },
        { skill: 'TH_SENTENCES', name: 'คำเชื่อมวิเศษ', activity: 'TRAIN', difficulty: 3 },
        { skill: 'TH_IDIOMS', name: 'สำนวนสัตว์', activity: 'MAGIC', difficulty: 1 },
        { skill: 'TH_IDIOMS', name: 'ใช้สำนวนให้ถูก', activity: 'PUZZLE', difficulty: 4 },
        { skill: 'TH_COMPREHENSION_ADV', name: 'อ่านหาเหตุผล', activity: 'TARGET', difficulty: 2 },
        { skill: 'TH_COMPREHENSION_ADV', name: 'ข้อเท็จจริงหรือความเห็น', activity: 'RACING', difficulty: 4 },
        { skill: 'TH_WORD_TYPES', name: 'ครอบครัวชนิดของคำ', activity: 'PUZZLE', difficulty: 1 },
        { skill: 'TH_WORD_TYPES', name: 'คำเดียวหลายหน้าที่', activity: 'MAGIC', difficulty: 5 },
      ],
      boss: { name: 'นกยูงทองผู้รอบรู้', emoji: '🦚', difficulty: 3 },
    },
    {
      code: 'BLOCK_VILLAGE',
      name: 'Block Word Village',
      nameTh: 'หมู่บ้านบล็อกคำไทย',
      emoji: '🛖',
      theme: 'craft',
      stages: [
        { skill: 'TH_WORDS', name: 'ขุดหาคำในบล็อก', activity: 'MINING', difficulty: 2 },
        { skill: 'TH_TONES', name: 'บล็อกวรรณยุกต์', activity: 'MINING', difficulty: 2 },
        { skill: 'TH_SPELLING', name: 'สร้างบ้านคำถูก', activity: 'BUILDING', difficulty: 2 },
        { skill: 'TH_FINAL_SOUNDS', name: 'เหมืองตัวสะกด', activity: 'MINING', difficulty: 2 },
        { skill: 'TH_CLASSIFIERS', name: 'นับของในหีบ', activity: 'BUILDING', difficulty: 2 },
        { skill: 'TH_IDIOMS', name: 'สำนวนในถ้ำลับ', activity: 'MINING', difficulty: 2 },
      ],
      boss: { name: 'หมาป่าจอมขโมยคำ', emoji: '🐺', difficulty: 3 },
    },
  ],
  items: [
    { code: 'GOLDEN_ROOSTER', name: 'ไก่ทองคำ', slot: 'PET', emoji: '🐓', price: null, rewardWorldCode: 'KOR_KAI_VILLAGE' },
    { code: 'MAGIC_BOOK', name: 'หนังสือวิเศษ', slot: 'ACCESSORY', emoji: '📕', price: null, rewardWorldCode: 'STORY_LIBRARY' },
    { code: 'STRAW_HAT', name: 'งอบชาวสวน', slot: 'HAT', emoji: '👒', price: null, rewardWorldCode: 'FLOATING_MARKET' },
    { code: 'GOLDEN_PEACOCK', name: 'นกยูงทอง', slot: 'PET', emoji: '🦚', price: null, rewardWorldCode: 'WISDOM_PALACE' },
    { code: 'WOLF_PUP', name: 'ลูกหมาป่าเพื่อนซี้', slot: 'PET', emoji: '🐺', price: null, rewardWorldCode: 'BLOCK_VILLAGE' },
  ],
};

// ───────────── 🧩 Logical thinking & problem solving ─────────────

export const LOGIC: CurriculumDef = {
  skills: [
    { code: 'LOG_PATTERNS', group: 'LOG_PATTERNS', name: 'Patterns', nameTh: 'แบบรูปและลำดับ', grade: 'K2', prerequisites: [] },
    { code: 'LOG_ODD_ONE_OUT', group: 'LOG_CLASSIFY', name: 'Odd One Out', nameTh: 'หาสิ่งที่ไม่เข้าพวก', grade: 'K3', prerequisites: [] },
    { code: 'LOG_SEQUENCE', group: 'LOG_PATTERNS', name: 'Sequences', nameTh: 'ลำดับวันและเดือน', grade: 'P1', prerequisites: ['LOG_PATTERNS'] },
    { code: 'LOG_DIRECTIONS', group: 'LOG_SPATIAL', name: 'Directions & Maps', nameTh: 'ทิศทางและแผนที่', grade: 'P2', prerequisites: [] },
    { code: 'LOG_ANALOGY', group: 'LOG_CLASSIFY', name: 'Analogies', nameTh: 'อุปมาอุปไมย', grade: 'P2', prerequisites: ['LOG_ODD_ONE_OUT'] },
    { code: 'LOG_NUMBER_PUZZLES', group: 'LOG_PATTERNS', name: 'Number Sequences', nameTh: 'ลำดับตัวเลขปริศนา', grade: 'P3', prerequisites: ['LOG_PATTERNS'] },
    { code: 'LOG_CODING', group: 'LOG_ALGORITHM', name: 'Step-by-step Coding', nameTh: 'คิดแบบโปรแกรมเมอร์', grade: 'P3', prerequisites: ['LOG_SEQUENCE', 'LOG_DIRECTIONS'] },
    { code: 'LOG_DEDUCTION', group: 'LOG_REASONING', name: 'Deduction', nameTh: 'การอนุมาน', grade: 'P3', prerequisites: ['LOG_SEQUENCE', 'LOG_ANALOGY'] },
    { code: 'LOG_SYMBOLS', group: 'LOG_REASONING', name: 'Symbol Puzzles', nameTh: 'ปริศนาสัญลักษณ์', grade: 'P4', prerequisites: ['LOG_DEDUCTION'] },
    { code: 'LOG_COMBINATIONS', group: 'LOG_REASONING', name: 'Counting Ways', nameTh: 'นับวิธีที่เป็นไปได้', grade: 'P5', prerequisites: ['LOG_NUMBER_PUZZLES'] },
    { code: 'LOG_TRUTH', group: 'LOG_REASONING', name: 'If-then Reasoning', nameTh: 'ตรรกะเงื่อนไข', grade: 'P5', prerequisites: ['LOG_DEDUCTION'] },
    { code: 'LOG_GRID_LOGIC', group: 'LOG_REASONING', name: 'Grid Logic', nameTh: 'ปริศนาตารางตรรกะ', grade: 'P6', prerequisites: ['LOG_TRUTH'] },
  ],
  placementStart: { K1: 'LOG_PATTERNS', K2: 'LOG_PATTERNS', K3: 'LOG_ODD_ONE_OUT', P1: 'LOG_SEQUENCE', P2: 'LOG_ANALOGY', P3: 'LOG_ANALOGY', P4: 'LOG_DEDUCTION', P5: 'LOG_SYMBOLS', P6: 'LOG_SYMBOLS' },
  worlds: [
    {
      code: 'PUZZLE_CASTLE',
      name: 'Puzzle Castle',
      nameTh: 'ปราสาทปริศนา',
      emoji: '🏯',
      theme: 'puzzle',
      stages: [
        { skill: 'LOG_PATTERNS', name: 'ลูกปัดเรียงสี', activity: 'BUILDING', difficulty: 1 },
        { skill: 'LOG_PATTERNS', name: 'แบบรูปซับซ้อน', activity: 'PUZZLE', difficulty: 4 },
        { skill: 'LOG_ODD_ONE_OUT', name: 'ใครไม่เข้าพวก', activity: 'TARGET', difficulty: 1 },
        { skill: 'LOG_ODD_ONE_OUT', name: 'จำนวนแปลกแยก', activity: 'TARGET', difficulty: 5 },
        { skill: 'LOG_SEQUENCE', name: 'ปฏิทินวิเศษ', activity: 'TRAIN', difficulty: 2 },
      ],
      boss: { name: 'สฟิงซ์ไขปริศนา', emoji: '🦁', difficulty: 2 },
    },
    {
      code: 'DETECTIVE_TOWER',
      name: 'Detective Tower',
      nameTh: 'หอคอยนักสืบ',
      emoji: '🕵️',
      theme: 'detective',
      stages: [
        { skill: 'LOG_ANALOGY', name: 'คู่ที่เหมือนกัน', activity: 'PUZZLE', difficulty: 1 },
        { skill: 'LOG_ANALOGY', name: 'คู่จำนวน', activity: 'MAGIC', difficulty: 5 },
        { skill: 'LOG_DEDUCTION', name: 'ใครสูงที่สุด', activity: 'RACING', difficulty: 1 },
        { skill: 'LOG_DEDUCTION', name: 'คดีลำดับ 4 คน', activity: 'TRAIN', difficulty: 3 },
        { skill: 'LOG_SYMBOLS', name: 'ผลไม้แทนเลข', activity: 'SHOP', difficulty: 2 },
        { skill: 'LOG_SYMBOLS', name: 'รหัสลับสองบรรทัด', activity: 'MAGIC', difficulty: 5 },
      ],
      boss: { name: 'จอมโจรปริศนา', emoji: '🦹', difficulty: 3 },
    },
    {
      code: 'ROBOT_FACTORY',
      name: 'Robot Factory',
      nameTh: 'โรงงานหุ่นยนต์',
      emoji: '🤖',
      theme: 'robot',
      stages: [
        { skill: 'LOG_DIRECTIONS', name: 'หุ่นยนต์หันซ้ายขวา', activity: 'RACING', difficulty: 1 },
        { skill: 'LOG_DIRECTIONS', name: 'เข็มทิศพาเดิน', activity: 'TRAIN', difficulty: 3 },
        { skill: 'LOG_DIRECTIONS', name: 'แผนที่ขุมทรัพย์', activity: 'MINING', difficulty: 4 },
        { skill: 'LOG_CODING', name: 'คำสั่งแรกของหุ่นยนต์', activity: 'BUILDING', difficulty: 1 },
        { skill: 'LOG_CODING', name: 'สามคำสั่งต่อกัน', activity: 'MAGIC', difficulty: 3 },
        { skill: 'LOG_CODING', name: 'วนซ้ำให้ไว', activity: 'TRAIN', difficulty: 4 },
        { skill: 'LOG_NUMBER_PUZZLES', name: 'ตัวเลขเรียงแถว', activity: 'TARGET', difficulty: 1 },
        { skill: 'LOG_NUMBER_PUZZLES', name: 'คูณทวีคูณ', activity: 'FISHING', difficulty: 3 },
      ],
      boss: { name: 'ไวรัสจอมป่วน', emoji: '👾', difficulty: 3 },
    },
    {
      code: 'BRAIN_OLYMPICS',
      name: 'Brain Olympics',
      nameTh: 'โอลิมปิกสมองใส',
      emoji: '🏅',
      theme: 'olympic',
      stages: [
        { skill: 'LOG_NUMBER_PUZZLES', name: 'ลำดับสุดพิศวง', activity: 'RACING', difficulty: 5 },
        { skill: 'LOG_CODING', name: 'ถอดรหัสย้อนกลับ', activity: 'MAGIC', difficulty: 5 },
        { skill: 'LOG_COMBINATIONS', name: 'แต่งตัวกี่แบบ', activity: 'SHOP', difficulty: 1 },
        { skill: 'LOG_COMBINATIONS', name: 'จัดแถวนักกีฬา', activity: 'PUZZLE', difficulty: 4 },
        { skill: 'LOG_TRUTH', name: 'ถ้า…แล้ว…', activity: 'TARGET', difficulty: 1 },
        { skill: 'LOG_TRUTH', name: 'ใครพูดจริง', activity: 'MAGIC', difficulty: 4 },
        { skill: 'LOG_GRID_LOGIC', name: 'ใครเลี้ยงอะไร', activity: 'PUZZLE', difficulty: 2 },
        { skill: 'LOG_GRID_LOGIC', name: 'ปริศนาสี่คน', activity: 'TRAIN', difficulty: 5 },
      ],
      boss: { name: 'พ่อมดปริศนา', emoji: '🧙', difficulty: 4 },
    },
    {
      code: 'BLOCK_MAZE',
      name: 'Block Maze',
      nameTh: 'เขาวงกตบล็อก',
      emoji: '🗺️',
      theme: 'mine',
      stages: [
        { skill: 'LOG_PATTERNS', name: 'เรียงบล็อกเป็นลาย', activity: 'BUILDING', difficulty: 3 },
        { skill: 'LOG_DIRECTIONS', name: 'เดินในเขาวงกต', activity: 'MINING', difficulty: 4 },
        { skill: 'LOG_DIRECTIONS', name: 'หาทางออกจากถ้ำ', activity: 'MINING', difficulty: 5 },
        { skill: 'LOG_CODING', name: 'สั่งหุ่นขุดแร่', activity: 'BUILDING', difficulty: 2 },
        { skill: 'LOG_CODING', name: 'วนลูปขุดอุโมงค์', activity: 'MINING', difficulty: 4 },
        { skill: 'LOG_COMBINATIONS', name: 'ผสมบล็อกได้กี่แบบ', activity: 'MINING', difficulty: 2 },
        { skill: 'LOG_GRID_LOGIC', name: 'ใครเจอสมบัติ', activity: 'MINING', difficulty: 3 },
      ],
      boss: { name: 'งูยักษ์เขาวงกต', emoji: '🐍', difficulty: 4 },
    },
  ],
  items: [
    { code: 'PUZZLE_PIECE', name: 'จิ๊กซอว์ทองคำ', slot: 'ACCESSORY', emoji: '🧩', price: null, rewardWorldCode: 'PUZZLE_CASTLE' },
    { code: 'DETECTIVE_GLASS', name: 'แว่นขยายนักสืบ', slot: 'ACCESSORY', emoji: '🔍', price: null, rewardWorldCode: 'DETECTIVE_TOWER' },
    { code: 'ROBOT_PET', name: 'หุ่นยนต์จิ๋ว', slot: 'PET', emoji: '🤖', price: null, rewardWorldCode: 'ROBOT_FACTORY' },
    { code: 'GOLD_MEDAL', name: 'เหรียญทองสมองใส', slot: 'ACCESSORY', emoji: '🏅', price: null, rewardWorldCode: 'BRAIN_OLYMPICS' },
    { code: 'TREASURE_MAP', name: 'แผนที่สมบัติ', slot: 'ACCESSORY', emoji: '📜', price: null, rewardWorldCode: 'BLOCK_MAZE' },
  ],
};
